### ISSUE TITLE
Why does this app use these permissions?

### ISSUE THREAD

**Issue by XinyueZ** [Thereisnospon/AcClient#14]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_LOGS" />

**Comment by Thereisnospon** [comment]
crash-report (bugly)

**Comment by XinyueZ** [comment]
I think the app needs "runtime permission check" code at splash status, how do you think?
